<?php
/**
 * @package RcitJobListings
 */

namespace Inc\Base;

use \Inc\Base\BaseController;

class SettingsLinks extends BaseController
{
    public function register() {
        add_filter( "plugin_action_links_$this->plugin_basename", array( $this, 'settings_link' ) );
    }

    /**
     * 
     * Pushes custom settings link to array of links
     * generated by WordPress
     * @return array Full list of links for the plugin
     */
    public function settings_link( $links ) {
        $settingsLink = '<a href="admin.php?page=rcit_job_listings">Settings</a>';
        array_push( $links, $settingsLink );
        
        return $links;
    }
}